# Generated by Django 5.0.6 on 2026-07-20 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount (optional). Must be greater than current price.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
