# Generated by Django 5.0.6 on 2026-07-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('B', 'Buyer'), ('S', 'Seller')], default='B', max_length=1),
        ),
    ]
