# Generated by Django 5.0.6 on 2026-07-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shop_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
