# Generated by Django 5.0.6 on 2026-07-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bank_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='provider_response',
        ),
        migrations.AddField(
            model_name='payment',
            name='encrypted_bank_reference',
            field=models.TextField(blank=True, help_text='AES-256 Encrypted Bank Reference'),
        ),
        migrations.AddField(
            model_name='payment',
            name='encrypted_provider_response',
            field=models.TextField(blank=True, help_text='AES-256 Encrypted Stripe/Provider Response'),
        ),
    ]
